package com.hawkhorse.fantasycharge.persistence.mapper;

import com.hawkhorse.fantasycharge.persistence.model.TUserLoginStatus;
import com.hawkhorse.fantasycharge.persistence.model.TUserLoginStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserLoginStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int countByExample(TUserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int deleteByExample(TUserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int insert(TUserLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int insertSelective(TUserLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    List<TUserLoginStatus> selectByExample(TUserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    TUserLoginStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TUserLoginStatus record, @Param("example") TUserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TUserLoginStatus record, @Param("example") TUserLoginStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUserLoginStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUserLoginStatus record);
}